ref. https://www.tensorflow.org/guide/keras/sequential_model

In [ ]:
%pip install -q -r ../requirements.txt


[notice] A new release of pip is available: 23.1.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf
import keras
from keras import layers

In [ ]:
# Define Sequential model with 3 layers
num_classes = 10
model = keras.Sequential(
    name="sequential",
    layers=[
        # keras.Input(shape=(2,)),
        layers.Dense(4, activation="relu", name="layer1"),  # , input_shape=(2,)
        layers.Dense(5, activation="relu", name="layer2"),
        layers.Dense(6, name="layer3"),
    ]
)
model.add(layers.Dense(num_classes, name="layer4", activation='softmax'))
model.layers

# [<Dense name=layer1, built=False>,
#  <Dense name=layer2, built=False>,
#  <Dense name=layer3, built=False>,
#  <Dense name=layer4, built=False>]

[<Dense name=layer1, built=False>,
 <Dense name=layer2, built=False>,
 <Dense name=layer3, built=False>,
 <Dense name=layer4, built=False>]

In [ ]:
print("Before calling the model, without input_shape.")
print(f"{len(model.weights)} weights")
print('=' * 16)
print(model.summary())

# Before calling the model, without init_shape.
# 0 weights
# ================
# Model: "sequential"
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
# ┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
# ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
# │ layer1 (Dense)                  │ ?                      │   0 (unbuilt) │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ layer2 (Dense)                  │ ?                      │   0 (unbuilt) │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ layer3 (Dense)                  │ ?                      │   0 (unbuilt) │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ layer4 (Dense)                  │ ?                      │   0 (unbuilt) │
# └─────────────────────────────────┴────────────────────────┴───────────────┘
# Total params: 0 (0.00 B)
#  Trainable params: 0 (0.00 B)
#  Non-trainable params: 0 (0.00 B)

Number of weights before calling the model: 0


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer3 (Dense)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer4 (Dense)                  │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [6]:
# Call model on a test input
x = tf.ones((2, 3))
print(x)
print('=' * 16)
y = model(x)
print(y)

# tf.Tensor(
# [[1. 1. 1.]
#  [1. 1. 1.]], shape=(2, 3), dtype=float32)
# ================
# tf.Tensor(
# [[ 0.1843983  -0.05233091  0.1072094   0.3583037  -0.20855665 -0.16213575
#   -0.00953133]
#  [ 0.1843983  -0.05233091  0.1072094   0.3583037  -0.20855665 -0.16213575
#   -0.00953133]], shape=(2, 7), dtype=float32)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]], shape=(2, 7), dtype=float32)


In [ ]:
print("After calling the model")
print(f"{len(model.weights)} weights: {model.weights[:10]} ...")
print('=' * 16)
print(model.summary())

# After calling the model: [<KerasVariable shape=(3, 4), dtype=float32, path=sequential/layer1/kernel>,
# 8 weights :
# ================
# Model: "sequential"
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
# ┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
# ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
# │ layer1 (Dense)                  │ (2, 4)                 │            16 │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ layer2 (Dense)                  │ (2, 5)                 │            25 │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ layer3 (Dense)                  │ (2, 6)                 │            36 │
# ├─────────────────────────────────┼────────────────────────┼───────────────┤
# │ layer4 (Dense)                  │ (2, 7)                 │            49 │
# └─────────────────────────────────┴────────────────────────┴───────────────┘
#  Total params: 126 (504.00 B)
#  Trainable params: 126 (504.00 B)
#  Non-trainable params: 0 (0.00 B)

8 weights after calling the model: [<KerasVariable shape=(3, 4), dtype=float32, path=sequential/layer1/kernel>, <KerasVariable shape=(4,), dtype=float32, path=sequential/layer1/bias>, <KerasVariable shape=(4, 5), dtype=float32, path=sequential/layer2/kernel>, <KerasVariable shape=(5,), dtype=float32, path=sequential/layer2/bias>, <KerasVariable shape=(5, 6), dtype=float32, path=sequential/layer3/kernel>, <KerasVariable shape=(6,), dtype=float32, path=sequential/layer3/bias>, <KerasVariable shape=(6, 7), dtype=float32, path=sequential/layer4/kernel>, <KerasVariable shape=(7,), dtype=float32, path=sequential/layer4/bias>] ...


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (2, 4)                 │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (2, 5)                 │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer3 (Dense)                  │ (2, 6)                 │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer4 (Dense)                  │ (2, 7)                 │            49 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 126 (504.00 B)

 Trainable params: 126 (504.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.compile(
    optimizer=keras.optimizers.Adam, 
    loss=keras.losses.CategoricalCrossentropy, 
    metrics=[keras.metrics.Accuracy]
)

model.build()

In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1).astype('float32') / 255
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1).astype('float32') / 255
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

In [ ]:
model.fit(
    x_train, 
    y_train,
    validation_data=(x_test, y_test),  # validation_split=0.2
    epochs=10,
    batch_size=200, 
    verbose=2
)

In [ ]:
test_scores = model.evaluate(
    x_test,
    y_test, 
    verbose=0
)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])

In [ ]:
model.save("PAT/TO/model.keras")

In [ ]:
if model:
    del model

# Recreate the exact same model purely from the file:
model = keras.models.load_model("PAT/TO/model.keras")